name: BlobEnderchest
version: ${project.version}
main: us.mytheria.blobenderchest.BlobEnderchest
api-version: 1.17
load: STARTUP
depend: [ BlobLib ]
commands:
  blobenderchest:
    description: BlobEnderchest command